import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "./fonts";
import { SearchProvider } from "./context/useSearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <SearchProvider>{children}</SearchProvider> */}
      </body>
    </html>
  );
}
